### ISSUE TITLE
How does browser communicate with server where api is located?

### ISSUE THREAD

**Issue by Fionaussie** [codelovers/asana-time-track#11]
Hi there! Guttentag!

"The easiest way is to download the zip-file ( https://github.com/codelovers/asana-time-track/archive/master.zip ) and extract it.
After that you have to upload it onto your server (the server has to interpret php). 
More informations you can find here http://codelovers.github.com/asana-time-track/ ."

OK, I"ve done this, but how in the heck do the browser and the server communicate? We are a small company with fewer than 30 users so we use Asana over the internet using our browsers. Is the information above meant for larger users who have Asana installed on their own servers?

Thanks!
Fiona

**Comment by monbro** [comment]
No, the size of your company doesnt matter. And as i know it is not possible to install asana on your own server.
The script needs PHP to work, so just put the script on a php/apache server and open the installation dir in your browser.
