### ISSUE TITLE
Manual editing of estimated and worked time isn't saved

### ISSUE THREAD

**Issue by hseagle2015** [codelovers/asana-time-track#14]
Hi,

I've just checked out the latest revision of asana-time-track app and while testing all the features I noticed that if I manually edit estimated and/or worked time, the changes aren't being saved on Asana. This is really annoying, escpecially since your app is capable to update elapsed time if I use the timer (start/stop button).

Is this a known issue or do I really have to visit Asana's website, find the task I was working on and manually edit the times in task's title?

Cheers!

**Comment by hseagle2015** [comment]
I've just noticed that if I try to edit times manually, the request.php script returns the following response:

<p>ERROR: Something went wrong! Maybe your asana api key does not fit.<br/> Or you have no internet connection.</p>

This is strange because in every other aspect asana-time-track app is able to communicate with Asana's API without any problems :confused:

**Comment by MartinKolb1987** [comment]
hi, this is really strange ^^. it works fine for me. i´ve tested it on my machine again and again.

**Comment by hseagle2015** [comment]
Yes, it appears that there was a temporary glitch between my server and Asana's. I haven't made any changes and now it's working just fine.

**Comment by MartinKolb1987** [comment]
great :-)
