### ISSUE TITLE
Not pulling any tasks through to our TimeTracker

### ISSUE THREAD

**Issue by briancalifano** [codelovers/asana-time-track#17]
We have recently added your files to a directory on our server to start using TimeTracker - we've synched up the API key correctly and it's not loading any tasks in from our projects in Asana - it's pulling in one task randomly on a colleagues computer but otherwise not working at all - any recommendations - this is exactly what we're looking for and would love it to work!

**Comment by monbro** [comment]
have you tried it on a apache/php server out of the box?
have you tried it in another browser with the latest version?
maybe there are some problems with your server configuration?

**Comment by briancalifano** [comment]
Fixed this - had to put it on a different server running a different
version of PHP.. working now - thanks!

**\* Side note -it would be good to be able to use Subtasks more efficiently
- i.e. indent subtasks with a different background color underneath main
  tasks...

On Thu, Jan 17, 2013 at 2:05 PM, Michael Klein notifications@github.comwrote:

> have you tried it on a apache/php server out of the box?
> have you tried it in another browser with the latest version?
> maybe there are some problems with your server configuration?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/codelovers/asana-time-track/issues/17#issuecomment-12383514.

## 

Best Regards,

_BRIAN CALIFANO_
_DESIGN & DEVELOPMENT PRINCIPAL_

Direct: 732-749-8334
T: 1-866-772-GEEK
T: 732-223-6700 ext. 103
F: 1-866-423-2558
602 Main Street Unit C, Belmar, NJ 07719
brian@semgeeks.com
www.semgeeks.com
www.semgeeks.net
_New!_  http://www.njwebdesign.org
-  Join the SEMGeeks Social
  Mediasphere!http://www.facebook.com/pages/SEMGeekscom/265037659413?sk=app_7146470109
  *

CONFIDENTIALITY NOTICE: This transmission (including any attachments) may
contain confidential information, privileged material (including material
protected by the solicitor-client or other applicable privileges), or
constitute non-public information. Any use of this information by anyone
other than the intended recipient is prohibited. If you have received this
transmission in error, please immediately reply to the sender and delete
this information from your system. Use, dissemination, distribution, or
reproduction of this transmission by unintended recipients is not
authorized and may be unlawful.
