### ISSUE TITLE
Exposed code

### ISSUE THREAD

**Issue by Wellnerr** [codelovers/asana-time-track#19]
I've tried installing into Tomcat 6, and everything seems find until I enter my API number.  After so, I see a lot of the code from the request.php.  CSS and images appear to be unaffected, so I'm a little unsure where the breakdown occurred.  Has anything experienced this or am I doing something incorrectly here?
![Asanatt](https://f.cloud.github.com/assets/3359287/91516/91f707a0-65a3-11e2-81ed-7a02a191e85d.png)

**Comment by MartinKolb1987** [comment]
Hi. It seems to be the wrong "Apache-Server". The Apache-Tomcat-Server is a Java-Server. It interprets normally only Java. (There is an PHP/Java Bridge http://php-java-bridge.sourceforge.net/doc/tomcat6.php , but it´s a bit complicated). BETTER, just try to download xampp (http://www.apachefriends.org/de/index.html) and put the asana-time-track-folder into the htdocs directory.

**Comment by Wellnerr** [comment]
Great, I ended up going with Xampp.  Was under the wrong impression that xwiki ran on PHP.  I may try the bridge later on, just wanted to test this out.  Anyway It appears to be running correctly, but now when I have a task, I see these three lines of code.  Any suggestions?

![image](https://f.cloud.github.com/assets/3359287/94062/7c422254-663f-11e2-82e0-c9f8e8a4046f.png)

**Comment by Wellnerr** [comment]
Got the line 66 fixed through some code proposed by another user and the request.php error seems to be caused when the Task has no Project assigned to it.
