### ISSUE TITLE
Skip Modal Box

### ISSUE THREAD

**Issue by knr481** [codelovers/asana-time-track#24]
Is there a way to hard code the API and Projects workspace into the code, so I don't have to enter it each time?

**Comment by MathiasTim** [comment]
To enter the Api-Key in your fork of the code just change line 60 of Index.php written below... ([this file](https://github.com/codelovers/asana-time-track/blob/master/index.php#L60))

``` html
 <input type="text" id="api-key" required val="Enter your Api-Key here">
```

For the automatic selection of your workspace, i got no quick solution, some dirty try maybe with [jquery trigger](http://api.jquery.com/trigger/) when trigger a click on the first element in the [workspace container](https://github.com/codelovers/asana-time-track/blob/master/index.php#L81)

hope this is helpful for you.

Regards, Mathias
