### ISSUE TITLE
HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy

### ISSUE THREAD

**Issue by zirconiums** [codelovers/asana-time-track#28]
hello -- am excited to try this project for asana. after using the demo for look-feel, i installed on apache 2.22 with php. i am writing here to document the fix steps i took to resolve several issues.

PROBLEM
--the index page loads and i can load my api key and click submit.
--the popup changes and appears to be calling the api, and the spin (in-progress) graphic spins, but nothing happens.

I checked it with Firebug and received the following:

HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy
.../js/js-libs/jquery/jquery.js   Line 6357

fragment.appendChild( ret[i] );

RESOLUTION:
1. verify php is working on your server.
     a. create a info.php file with the following code and save it to your server's root folder.
<html>
<head>
<title>PHP Test Script </title>
</head>
<body>
<?php
phpinfo();
?>
</body>
</html>
     b. point your browser at the document (../info.php)
     c. verify php is working
1. if PHP is not working, make sure the module is installed
2. and then use the utility a2enmod to add it to the mods-enabled pack
3. restart your apache

**Comment by zirconiums** [comment]
i honestly don't know HOW a stock ubuntu install of apache did not include php5. but there you go.

**Comment by MathiasTim** [comment]
I dont think this is related to the code in asana time track, because apache, php and curl are requirements for att.
Thanks for your issue anyway, but thats why we recommend using XAMPP, MAMP, etc...
