### ISSUE TITLE
NetworkError: 500 Internal Server Error - http://localhost/request.php?apiKey=...

### ISSUE THREAD

**Issue by zirconiums** [codelovers/asana-time-track#29]
hello again -- just documenting what i did to fix this along the way.

SYMPTOMS / PROBLEM
(using firebug extension for firefox, i stepped through the load process of the index.php) 
-- completed my api key and clicked submit, but nothing happens
-- error on GET http://localhost/request.php?apiKey=...
-- NetworkError: 500 Internal Server Error
-- /var/log/apache2/error.log error: "PHP Fatal error:  Call to undefined function curl_init() in /var/www/AsanaApi.php on line 129"

RESOLUTION
(I don't know _HOW_ CURL could not be installed with a stock-install of apache, but the curl module for php was not installed on mine)
1. using your favorite package installer, find php5-curl and install.
2. if needed, restart your apache server
(ubuntu package manager will automatically restart your server with the new module; check the install log for details.

**Comment by MathiasTim** [comment]
I dont think this is related to the code in asana time track, because apache, php and curl are requirements for att.
Thanks for your issue anyway, but thats why we recommend using XAMPP, MAMP, etc...
