### ISSUE TITLE
Edit Time Track Bug

### ISSUE THREAD

**Issue by MathiasTim** [codelovers/asana-time-track#3]
I'm little confused on adding the time manually in the tracking tool. Though I add it manually, it gets reset and just pulls the data from the Asana database after the refresh. Whatever I add in the time track tool gets reset after refresh, so I hope its better to just maintain the [ET] and [WT 0h:0h] within Asana. Please correct me if I'm missing wrong.
-- Posted by Arun Kumar via Email

**Comment by MathiasTim** [comment]
we will correct this as soon as possible

**Comment by arunmitteam** [comment]
Thanks for looking into it!
- Arun

**Comment by shuairan** [comment]
Can you try to wait a little longer after changing something in the time track tool? It's supposed to update the ticket title on Asana with the changed WT and ET times, but at my local setup the updating script runs about 10 to 20sec.

If I hit "Update" before the request was completed the changes are overwritten by the old values from Asana. I'll also try to figure out why the api-request is so slow, but it would be helpful if you could try waiting after editing.

Apart from that a visual feedback in the time tracking tool which shows if the update was successful would be nice...

**Comment by marvinone** [comment]
shuairan +1

same here!

**Comment by MartinKolb1987** [comment]
thanx for your information!
We added some more request-handling-stuff --> if you change your WT or ET manual, the "update" button is disabled. No  more request is possible at this time.
