### ISSUE TITLE
How to run as localhost

### ISSUE THREAD

**Issue by uncompromise** [codelovers/asana-time-track#32]
Admittedly, my technical skills are limited :/

I have installed xampp in my apps container, parsed the package and can get the service running.

However, while I can see my various workspaces, I cannot sync any tasks, including those assigned to me. See the attached screenshot.

I have refreshed my Asana API key, but no luck.

Thoughts?
![screen shot 2013-06-25 at 11 27 38 pm](https://f.cloud.github.com/assets/4602460/707699/772bfc5a-de2a-11e2-9124-f6b8e356be8f.png)

**Comment by bituka** [comment]
use this - http://asanatimetrack.tk/

**Comment by uncompromise** [comment]
awesome - nailed it; thanks

**Comment by MathiasTim** [comment]
just for clarification: asanatimetrack.tk is not from the original authors from codelovers.
It's just fine, stoned-code-warrior set up this service.
But please remember ALL your Data from Asana will be visible to the Servers of asanatimetrack.tk

(This is why we from codelovers did not set up something similar.)
