### ISSUE TITLE
Enhancement for time tracking of all resources

### ISSUE THREAD

**Issue by arunmitteam** [codelovers/asana-time-track#4]
Time track tool allows me to track my tasks, task progress and the actual time spent in each task. I have a requirement to track the tasks across projects. As a manager, there have been lot of instances where I wanted to see the slippage in estimated hours and follow up with the resource on that. Is there a plan to develop an admin manage for managers to view the overall status of the project? Please let me know, this would be of great help

Arun

**Comment by arunmitteam** [comment]
I'm unable to add the label "enhancement" to my post,  I guess only the collaborators/admin can assign label to an issue.

**Comment by MartinKolb1987** [comment]
Hey Arun,

about your question with the admin-thing. We do not plan to build an interface for admins,
because we had problems fetching too many tasks from asana. It often resulted in a server-time-out.
But thank you for your recommendation. We put it in our asana-feature-list.

Best wishes, Martin

**Comment by arunmitteam** [comment]
Hi Martin,
Thanks for the insight. I understand the design decision. Is it possible to
just list down all the projects from a workspace and then allow the admin
to select one project. We can list down all the tasks in one project. This
will limit the tasks to some extent I guess.

Thanks,
Arun

On Aug 20, 2012, at 1:04 PM, MartinKolb1987 notifications@github.com
wrote:

Hey Arun,

about your question with the admin-thing. We do not plan to build an
interface for admins,
because we had problems fetching too many tasks from asana. It often
resulted in a server-time-out.
But thank you for your recommendation. We put it in our asana-feature-list.

Best wishes, Martin

—
Reply to this email directly or view it on
GitHubhttps://github.com/codelovers/asana-time-track/issues/4#issuecomment-7875997.

**Comment by MartinKolb1987** [comment]
Hi Arun,

sure is it possible to do that. But at the moment we are very busy. We try to implement the selection-possibility as soon as possible.

Greetings, Martin
