### ISSUE TITLE
Asana Set up - Get Black Screen

### ISSUE THREAD

**Issue by pavanhemdev** [codelovers/asana-time-track#44]
After setting up Asana on our web server, we got a black screen.

Just to be clear, we uploaded all the files present in the git hub directly. 

![black screen](https://cloud.githubusercontent.com/assets/6211665/2799728/48b0b60c-cc65-11e3-845d-0cdfa18603ad.png)

**Comment by MartinKolb1987** [comment]
Hi... just check out the whole repo again.
![bildschirmfoto 2014-04-25 um 14 00 39](https://cloud.githubusercontent.com/assets/1842716/2800335/69e53b66-cc71-11e3-99a9-5869d7add163.png)

**Comment by pavanhemdev** [comment]
Aaah.. such a beginners mistake..... Thanks a ton..

**Comment by MartinKolb1987** [comment]
no problem :-)
