### ISSUE TITLE
increment javascript timeout in js/script.js

### ISSUE THREAD

**Issue by davdenic** [codelovers/asana-time-track#5]
Hello I increment timeouts from 30000 to 300000 in the functions tasksAjaxCall and changeTasksAjaxCall in js/script.js file.
This prevent the timeout error in case of tons of tasks like mine workspace.
Thanks.

**Comment by MartinKolb1987** [comment]
we are working after SCRUM and so we didn´t have problems like that because we have normally just one task assigned. The timeout is set to 90 sec. as default value now.
